#include "stm32f103xe.h"
#include "afio.h"

void AFIO_init(void)
{
	AFIO->MAPR |= AFIO_MAPR_USART3_REMAP_NOREMAP;
	
	AFIO->MAPR |= AFIO_MAPR_ADC1_ETRGINJ_REMAP;
	
	//AFIO->MAPR |= AFIO_MAPR_TIM1_REMAP_NOREMAP;
	//AFIO->MAPR |= AFIO_MAPR_TIM2_REMAP_PARTIALREMAP1; 
	
	
	AFIO->MAPR |= AFIO_MAPR_SWJ_CFG_DISABLE;

}