#include "stm32f103xe.h"
#include "rcc.h"

void RCC_init(void)
{
	
	//RCC->CR = 0;
	//RCC->CFGR = 0;
	
	RCC->CR |= RCC_CR_HSEON;
	
	while((RCC->CR & RCC_CR_HSERDY) == 0){}
	
	RCC->CFGR |= RCC_CFGR_PLLMULL_1 | RCC_CFGR_PLLSRC;
		

	FLASH->ACR |= FLASH_ACR_LATENCY_0; 		
		
	RCC->CR |= RCC_CR_PLLON;	
	while((RCC->CR & RCC_CR_PLLRDY) == 0){}
		
	RCC->CFGR &= (uint32_t)((uint32_t)~(RCC_CFGR_SW));
	RCC->CFGR |= RCC_CFGR_SW_PLL;	
		
	while((RCC->CFGR&RCC_CFGR_SWS_PLL) != RCC_CFGR_SWS_PLL){}
		
	//RCC->CR &= ~RCC_CR_HSION;
		
	RCC->CFGR &= ~RCC_CFGR_ADCPRE_0;  // prescaler ADC (/6)
	RCC->CFGR |=  RCC_CFGR_ADCPRE_1;		

		
		
	RCC->APB2ENR |= RCC_APB2ENR_IOPAEN | RCC_APB2ENR_IOPBEN | RCC_APB2ENR_IOPCEN | RCC_APB2ENR_IOPDEN;
	
	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;
		
	RCC->APB2ENR |= RCC_APB2ENR_USART1EN;	
	RCC->APB1ENR |= RCC_APB1ENR_USART3EN;
	
	RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;
	
	RCC->AHBENR |= RCC_AHBENR_DMA1EN;
		
	//RCC->APB2ENR |= RCC_APB2ENR_TIM1EN;		
	//RCC->APB1ENR |= RCC_APB1ENR_TIM2EN | RCC_APB1ENR_TIM3EN | RCC_APB1ENR_TIM4EN;
	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;

}